import "./store/index.js";
import "./store/connectionStore.js";
import "./control/net.js";
import "./utils/stats.js";
import "./styles.css";
import "./app.js";
import "./viewport";
import "./entities/world/worldMap.js";
import "./resources.js";
import "./visual.js";
import "./world";
// import "./react/index.jsx";
