import './store/index.js';
import './store/connection-store.js';
import './control/net.js';
import './utils/stats.js';
import './styles.css';
import './app';
import './viewport';
import './entities/world/world-map.js';
import './resources.js';
import './visual.js';
// import "./world";
// import "./react/index.jsx";
